spring:
  application:
    name: security-service
  config:
    import: optional:configserver:http://localhost:8081
security:
  jwt:
    key:
      private: "security.signature"
    user:
      generator: "voll.med"