server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JobjCaal3/medical-clinic.git
          search-paths: config-data
          default-label: main
  application:
    name: configurations

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    #cambiar por el nombre del contenedor
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
