server:
  port: 8081
spring:
  application:
    name: configurations
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JobjCaal3/medical-clinic.git
          search-paths: production-configuration-data
          default-label: configurations

