server:
  port: 0

spring:
  application:
    name: notify-center
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: medical-clinic-eureka-dicovery
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
